# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
inherit_from:
  - <%= `brew --prefix`.lines.first.chomp -%>/Homebrew/Library/.rubocop.yml
AllCops:
  Include:
    - Gemfile
    - Rakefile
    - Casks/*
    - Formulas/*
  Exclude:
   - bin/**/*
   - tmp/**/*
   - vendor/**/*
   - .github/**/*

Layout/LineLength:
  Max: 120

# Just disable this for our Tap
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
## Needs newer version of RuboCop than Homebrew has pinned
## Reference: https://github.com/rubocop/rubocop/issues/9399
#  IgnoredCops: ['Metrics/MethodLength', 'Layout/LineEndStringConcatenationIndentation']
